# Generated by Django 2.0.4 on 2018-04-18 23:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_mymodelname'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MyModelName',
        ),
        migrations.DeleteModel(
            name='posts',
        ),
    ]
