# Generated by Django 2.0.4 on 2018-04-23 18:00

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20180421_2048'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='file_upload',
            field=models.FileField(null=True, upload_to='files/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='file',
            name='upload_date',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
    ]
