# Generated by Django 2.0.4 on 2018-04-25 17:16

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_auto_20180423_1446'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='upload_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 4, 25, 17, 16, 36, 123307, tzinfo=utc), null=True),
        ),
    ]
